// Shared key-concept extraction for module exports (essay prompt, rubric, and
// the PDF "Petunjuk belajar" intro). One source of truth so the same class of
// bug cannot surface in three consumers at once.
//
// This module closes the corrupted-"key concepts" export defect:
//   1. Strip known template / boilerplate scaffolding BEFORE mining — the fixed
//      "Tujuan Pembelajaran" lead-in ("Setelah membaca modul ini, kamu bisa …")
//      is generated by the module template, not model content, so it must never
//      be treated as a course concept.
//   2. Operate on sentence / clause boundaries. Never truncate mid-word and
//      never cut inside markdown syntax (* _ [ ( — a raw character-count slice
//      is what produced the "(*Street," fragment inside a half-open bold marker.
//   3. Sanity filter every candidate: reject anything that starts with a generic
//      filler word or is too long / syntactically broken to be a term. This also
//      catches future template strings someone forgets to add to the strip-list.

const FILLER_PREFIXES = [
  "setelah",
  "topik",
  "dalam",
  "bagaimana",
  "untuk",
  "antara",
  "mengapa",
  "apa",
  "siapa",
  "kapan",
  "di",
  "ke",
  "pada",
  "sebagai",
  "yaitu",
  "berdasarkan",
  "menurut",
  "catatan",
  "contoh",
  "misalnya",
  "pertanyaan",
  "petunjuk",
  "modul",
  "ringkasan",
  "rangkuman",
  "latihan",
  "tugas",
  "kamu",
  "saya",
  "kita",
  "mereka",
  "bisa",
  "dapat",
  "sudah",
  "belum",
  "akan",
  "harus",
  "menjadi",
  "memiliki",
  "mengidentifikasi",
  "membedakan",
  "menjelaskan",
  "menggunakan",
  "melakukan",
  "menunjukkan",
  "memberikan",
  "mengetahui",
  "memahami",
];

// Whole sections that are pure template scaffolding (never hold concepts).
const TEMPLATE_SECTIONS = /(tujuan\s+pembelajaran|petunjuk\s+belajar|petunjuk\s+belajar|ringkasan|rangkuman)/i;

/** Removes markdown noise so sentence-splitting/scoring isn't fooled by syntax. */
function deMarkdown(text: string): string {
  return text
    .replace(/^[#*\s>]+/, "")
    .replace(/\[([^\]]+)\]\([^)]*\)/g, "$1") // links → label
    .replace(/\[\d+(?:\s*,\s*\d+)*\]/g, " ") // citation markers [1] / [1, 2] → gone
    .replace(/[*_`]/g, " ") // inline markdown markers → space
    .replace(/\s+/g, " ")
    .trim();
}

/**
 * Drops entire template sections (Tujuan Pembelajaran, Petunjuk belajar,
 * Ringkasan) from the module before any concept is mined. These are generated by
 * the synthesis template, not by the model's reasoning about the topic, so their
 * contents (e.g. "Setelah membaca modul ini, kamu bisa: …") must never become a
 * "concept".
 */
export function stripModuleBoilerplate(markdown: string): string {
  const lines = markdown.replace(/\r\n/g, "\n").split("\n");
  const out: string[] = [];
  let inTemplate = false;
  for (const line of lines) {
    if (/^\s{0,3}#{1,6}\s/.test(line)) {
      inTemplate = TEMPLATE_SECTIONS.test(line);
      if (inTemplate) continue; // drop the heading itself too
    }
    if (inTemplate) continue;
    out.push(line);
  }
  return out.join("\n");
}

/**
 * Splits a chunk of text into candidate atoms on clause boundaries (commas,
 * semicolons, sentence ends) — so a run-on like
 * "Aktor A, Aktor B, C (*Street," yields three clean terms and one rejected
 * broken fragment, instead of one giant garbage "concept".
 *
 * A definition marker (":", " - ", "adalah", …) marks the boundary between a
 * term and its explanation, so only the TERM side is kept — the explanation is
 * never mined as a second concept.
 */
function toAtoms(text: string): string[] {
  return termSide(text)
    .split(/[,;]|\s[-–—]\s|(?<=[\.\?!])\s+|\(/)
    .map((s) => deMarkdown(s))
    .map((s) => s.replace(/^[-*)\]]/, "").trim())
    .filter(Boolean);
}

/**
 * Keeps only the TERM side of a "term — explanation" / "term: explanation" /
 * "term adalah explanation" string. Used for both prose atoms and sub-heading
 * titles, since the synthesis template writes concept headings as
 * "### Nama Konsep — penjelasan".
 */
function termSide(text: string): string {
  return text.split(/:\s*|\s[-–—]\s|\s(?:adalah|merupakan|ialah)\s/i)[0] ?? text;
}

/** True when the atom is syntactically whole (no dangling markdown/bracket). */
function isSyntacticallyWhole(s: string): boolean {
  // Reject unbalanced inline markers — a concept must be clean text, never a
  // fragment sliced out of a `*bold*` or `[cite]` or `(paren`.
  const opens = (s.match(/[*_[(]/g) || []).length;
  const closes = (s.match(/[*_)\]]/g) || []).length;
  if (opens !== closes) return false;
  if (/\(\s*$/.test(s)) return false; // dangling open paren
  return true;
}

function isFiller(s: string): boolean {
  const first = s.split(/\s+/)[0]?.toLowerCase().replace(/[*_:.(]/g, "") ?? "";
  return FILLER_PREFIXES.includes(first);
}

/** Heading level (1–6) of a markdown heading line, or null when not a heading. */
function headingLevel(line: string): number | null {
  const m = /^\s{0,3}(#{1,6})\s+/.exec(line);
  return m ? m[1].length : null;
}

const CONCEPT_SECTION_HEADING =
  /^\s*#{0,6}\s*(?:\d+[.)]\s*)?(?:konsep\s+kunci|konsep\s+utama|definisi|istilah)\b/i;

/**
 * Accepts a candidate term or rejects it. `clampWords` limits prose atoms to a
 * few words (a run-on sentence is not a term); sub-heading titles are already
 * terms by construction, so they are kept whole (clampWords = null) — clamping
 * them would chop a legitimate four-plus-word concept name.
 */
function sanitizeConcept(
  raw: string,
  { clampWords, maxChars }: { clampWords: number | null; maxChars: number },
): string | null {
  let s = deMarkdown(raw).replace(/^[-*)\]\s]+/, "").replace(/[.,;:]+$/, "").trim();
  if (clampWords !== null) s = s.split(/\s+/).slice(0, clampWords).join(" ").trim();
  if (s.length < 3 || s.length > maxChars) return null; // term, not a sentence/clause
  if (isFiller(s)) return null;
  if (!isSyntacticallyWhole(s)) return null;
  return s;
}

/**
 * Extracts up to `limit` short key-concept terms from a module's markdown.
 *
 * Three candidate sources, in priority order, matching how the synthesis template
 * actually writes the "Konsep kunci & definisi" section (see the structure
 * contract in app/api/synthesize/route.ts):
 *   1. The sub-heading titles inside the section ("### Nama Konsep",
 *      "### Nama Konsep — penjelasan"). These are the authoritative terms — the
 *      template gives EVERY concept its own sub-section — so they are read
 *      first. Reading only the section's loose prose (as an earlier pass did)
 *      returned an empty list for every real module, silently dropping the
 *      concept list from the PDF intro, the essay question and the rubric.
 *   2. A numbered concept list ("1. **Nama**: …") written as flat prose.
 *   3. Bold lead-in concept definitions ("*Nama Konsep (English)*: definisi")
 *      when the AI writes the section as bold paragraphs instead of `###`
 *      sub-headings or a numbered list — each bold term is read whole.
 *   4. The intro prose / list items that sit directly under the section heading
 *      before the first sub-heading (older or flatter modules put the concepts
 *      there, sometimes as one comma-joined run-on).
 *
 * Robust by construction: boilerplate is stripped first, candidates are broken
 * into clause atoms (never truncated mid-word), and each candidate is
 * sanity-filtered (length window, no dangling syntax, no filler lead-in).
 * Returns clean, module-specific terms or an empty array when none qualify.
 */
export function extractKeyConcepts(markdown: string, limit = 6): string[] {
  const cleaned = stripModuleBoilerplate(markdown);
  const lines = cleaned.split("\n");

  const idx = lines.findIndex((l) => CONCEPT_SECTION_HEADING.test(l));
  if (idx === -1) return [];
  // A sub-heading is any heading DEEPER than the section's own level; a heading
  // at the same or a higher level ends the section. When the marker line is not
  // a heading at all (a bolded label), nothing can be deeper, so prose-only.
  const sectionLevel = headingLevel(lines[idx]) ?? 6;

  const headingTitles: string[] = [];
  const numberedEntries: string[] = [];
  const boldEntries: string[] = [];
  const introLines: string[] = [];
  let sawSubHeading = false;
  for (let i = idx + 1; i < lines.length; i++) {
    const level = headingLevel(lines[i]);
    if (level !== null) {
      if (level <= sectionLevel) break; // next top-level section: done
      sawSubHeading = true;
      headingTitles.push(lines[i].replace(/^\s{0,3}#{1,6}\s+/, ""));
      continue;
    }
    // Prose is only mined from the section INTRO (before the first concept
    // sub-heading). Body text inside a concept sub-section is its explanation
    // ("Contoh konkret: …", "Pertanyaan refleksi: …"), never a second term.
    if (!sawSubHeading) {
      const t = lines[i].replace(/^[-*]\s+/, "").trim();
      if (!t) continue;
      // A numbered concept entry ("1. **Nama Konsep**: definisi") is the
      // authoritative term list when the AI writes the section as a numbered
      // list instead of `###` sub-headings. Capture it WHOLE (the ordinal is
      // stripped here) so it is read as ONE term — not atomised at commas /
      // parens into garbage like "Aktor Selain Negara (Non" or "Pemetaan
      // Jaringan Aktor (Actor".
      const nm = t.match(/^\d+[.)]\s+([\s\S]*)$/);
      if (nm) {
        numberedEntries.push(nm[1]);
        continue;
      }
      // A bold lead-in concept definition ("*Nama Konsep (English)*: definisi")
      // is another way the AI writes the section — every concept as a bold
      // paragraph rather than a `###` sub-heading. Capture the bold term WHOLE
      // (the parenthetical English gloss is dropped on the heading path) so it is
      // read as ONE term, never atomised at commas / "&" / "dan" into garbage
      // like "Aktor Non-Negara Lokal dan" or "Masyarakat Digital dan Pelayanan".
      const bm = t.match(/^\*+([^*][\s\S]*?)\*+\s*[:—-]\s/);
      if (bm) {
        boldEntries.push(bm[1]);
        continue;
      }
      introLines.push(t);
    }
  }

  const concepts: string[] = [];
  const seen = new Set<string>();
  const push = (candidate: string | null): boolean => {
    if (!candidate) return false;
    const key = candidate.toLowerCase();
    if (seen.has(key)) return false;
    seen.add(key);
    concepts.push(candidate);
    return concepts.length >= limit;
  };

  // Priority order matches how the synthesis template may actually write the
  // section (the AI does not always honour the `###` sub-heading contract):
  //   1. `###` sub-heading titles — one concept per sub-section.
  //   2. A numbered concept list ("1. **Nama**: …") written as flat prose.
  //   3. Bold lead-in definitions ("*Nama (English)*: definisi") as paragraphs.
  //   4. Loose intro prose / a comma-joined run-on (older, flatter modules).
  // Structured sources win so connective tissue (e.g. the lead-in "Untuk
  // memahami lanskap hukum, …") is never mined as a concept.
   for (const title of headingTitles) {
     // The heading is the term: keep it whole, minus any "— penjelasan" tail and
     // any parenthetical gloss ("(*Street-Level Bureaucrat*)"), which is where
     // the old fixed-length slice used to cut inside a bold marker. Indonesian
     // academic concept names are often 50–70 chars (e.g. "Aktor Selain Negara
     // dalam Hukum Humaniter Internasional"), so the cap must be well above that
     // — otherwise legitimate long concepts are silently dropped from the rubric
     // and the essay prompt.
     if (push(sanitizeConcept(termSide(title).split("(")[0], { clampWords: null, maxChars: 90 })))
       return concepts;
   }

  for (const entry of numberedEntries) {
    // A numbered list entry is one term — prefer the bold wrapper, keep balanced
    // parentheticals (e.g. "(Actor-Network Mapping)"), drop the ": definisi" tail.
    if (push(conceptFromTerm(entry, 80))) return concepts;
  }

  // Bold lead-in concept definitions ("*Term (English)*: definisi") — used when
  // the AI writes the section as bold paragraphs instead of `###` sub-headings or
  // a numbered list. Same whole-term handling as the heading path (gloss dropped,
  // generous char cap) so long bilingual names survive intact.
  if (!headingTitles.length && !numberedEntries.length) {
    for (const raw of boldEntries) {
      if (
        push(
          sanitizeConcept(termSide(raw).split("(")[0], { clampWords: null, maxChars: 90 }),
        )
      )
        return concepts;
    }
  }

  if (!headingTitles.length && !numberedEntries.length) {
    for (const raw of introLines) {
      if (!raw) continue;
      for (const atom of toAtoms(raw)) {
        if (push(sanitizeConcept(atom, { clampWords: 4, maxChars: 42 }))) return concepts;
      }
    }
  }
  return concepts;
}

/**
 * Turns a concept heading / numbered-list-entry title into a clean term. Strips
 * markdown emphasis (preferring an explicit `**bold**` wrapper as the term) and
 * any "— penjelasan" / ": definisi" tail via `termSide`. `clampWords` is null:
 * concept names are terms by construction, so truncating them would chop a
 * legitimate multi-word concept ("Aktor Selain Negara (Non-State Armed Groups)
 * dalam Hukum Humaniter").
 */
function conceptFromTerm(raw: string, maxChars: number): string | null {
  let s = raw.trim();
  // Prefer an explicit emphasis wrapper as the term (e.g. "**Nama Konsep**").
  const emph = s.match(/\*\*(.+?)\*\*/) || s.match(/\*(.+?)\*/) || s.match(/_(.+?)_/);
  if (emph) s = emph[1];
  s = termSide(s);
  return sanitizeConcept(s, { clampWords: null, maxChars });
}
