// Post-generation normalizer for module markdown.
//
// Goal: fix a small set of cosmetic typos/formatting seen in real generated
// PDFs so the product does not look unfinished. The fixes are SAFE and
// DETERMINISTIC — they never touch citations, numbers, DOIs, URLs, academic
// terms, or section-heading meaning, and normalizeModule is IDEMPOTENT
// (running it twice yields the same output).

const PLACEHOLDER = ""; // private-use char, never expected in real text

/** Indonesian/English function words that stay lowercase in a title (unless first). */
const TITLE_SMALL = new Set<string>([
  "dan", "yang", "pada", "ke", "di", "dari", "untuk", "dengan", "atau", "serta",
  "the", "a", "an", "of", "and", "in", "on", "at", "to", "for", "with", "or", "by",
]);

/** Proper nouns / acronyms to preserve verbatim during title-casing. */
const TITLE_PROTECTED = ["Hukum Internasional", "Non-State", "Street-Level", "HI"];

function escapeRegExp(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/**
 * Title-case a short title string. Major words are capitalized; a small set of
 * function words stays lowercase unless it is the first word; protected proper
 * nouns and short all-caps acronyms (e.g. "HI", "PDF") are preserved verbatim.
 * Idempotent: title-casing an already title-cased string is a no-op.
 */
function titleCase(text: string): string {
  const store: string[] = [];
  let t = text;
  for (const p of TITLE_PROTECTED) {
    t = t.replace(new RegExp(escapeRegExp(p), "gi"), () => {
      const idx = store.length;
      store.push(p);
      return `${PLACEHOLDER}${idx}${PLACEHOLDER}`;
    });
  }

  const parts = t.split(/(\s+)/);
  let wordCount = 0;
  const out = parts.map((part) => {
    if (part === "" || /^\s+$/.test(part)) return part;

    const ph = part.match(new RegExp(`^${PLACEHOLDER}(\\d+)${PLACEHOLDER}$`));
    if (ph) return store[Number(ph[1])];

    const m = part.match(/^([^\p{L}]*)([\p{L}]+)(.*)$/u);
    if (!m) return part;
    const [, pre, core, post] = m;
    const lower = core.toLowerCase();
    const isFirst = wordCount === 0;
    wordCount += 1;

    if (!isFirst && TITLE_SMALL.has(lower)) return part;
    if (core === core.toUpperCase() && /[A-Z]/.test(core) && core.length <= 5) return part;

    return pre + core.charAt(0).toUpperCase() + core.slice(1).toLowerCase() + post;
  });
  return out.join("");
}

/**
 * Normalize the brand token ("So-study", "so-study", "SO-STUDY") to the
 * canonical "So-Study". Only in unambiguous brand contexts — at the start of a
 * line (a header like "So-study — <title>") or following a known footer phrase
 * ("Diekspor dari So-study") — never mid-sentence.
 */
function normalizeBrand(s: string): string {
  s = s.replace(
    /^(\s*)(So-study|so-study|SO-STUDY)(?=\s|[—–-]|$)/gm,
    "$1So-Study",
  );
  s = s.replace(
    /(Diekspor dari|Ekspor dari|Dibuat dengan|Dibuat oleh|Generated by)\s+(so-study|So-study|SO-STUDY)\b/gi,
    "$1 So-Study",
  );
  return s;
}

/**
 * Title-case the module's main title line only: the first H1 heading
 * ("# <title>") and/or a PDF-header line shaped "So-Study — <title>".
 * Section headings ("## ...") and body prose are never touched.
 */
function titleCaseTitleLine(s: string): string {
  return s
    .split("\n")
    .map((line) => {
      const h1 = line.match(/^#\s+(.+?)\s*$/);
      if (h1) return `# ${titleCase(h1[1])}`;

      const header = line.match(
        /^([ \t]*(?:So-Study|So-study|so-study|SO-STUDY)\s*[—–-]\s*)(.+?)\s*$/,
      );
      if (header) return `${header[1]}${titleCase(header[2])}`;

      return line;
    })
    .join("\n");
}

/**
 * Apply the conservative, deterministic fixes described in the module spec:
 *   1. "TIngkatan" → "Tingkatan" (targeted broken-casing only).
 *   2. "state[- – —]centric" with stray spaces / non-ASCII dashes → "state-centric".
 *   3. Brand token at line-start / in a footer phrase → "So-Study".
 *   4. Title-case the module's main title line (first H1 or PDF header).
 *   5. Idempotent.
 *   6. Citations, URLs, DOIs, numbers, and academic terms are left untouched.
 */
export function normalizeModule(markdown: string): string {
  let s = markdown;

  // 1. Targeted broken casing only — "Tingkatan"/"tingkatan" are untouched.
  s = s.replace(/TIngkatan/g, "Tingkatan");

  // 2. Normalize "state[- – —]centric" regardless of stray spaces or dash kind.
  s = s.replace(/state\s*[-–—]\s*centric/g, "state-centric");

  // 3. Brand token in header/footer contexts.
  s = normalizeBrand(s);

  // 4. Title line only.
  s = titleCaseTitleLine(s);

  return s;
}
