import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ServiceWorkerRegister from "./components/ServiceWorkerRegister";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "So-study — head-start pra-kuliah",
  description:
    "Kit belajar pra-kuliah: baca modul dari paper, tanya terjaga, dan latih diri (retrieval practice) sebelum kuliah.",
  // Generated by app/manifest.ts, which Next serves at exactly this URL. Safari
  // fetches the manifest WITHOUT credentials, so this URL must stay publicly
  // readable — if it ever gets gated behind the auth proxy, "Add to Home Screen"
  // silently degrades to a plain Safari bookmark instead of a standalone app.
  manifest: "/manifest.webmanifest",
  // iOS takes the home-screen icon from this link, not from the manifest icons;
  // the explicit 180x180 stops Safari from guessing and rescaling.
  icons: {
    apple: [{ url: "/apple-touch-icon.png", sizes: "180x180", type: "image/png" }],
  },
  // `capable: true` emits the standardised `mobile-web-app-capable`, which iOS
  // ignores — since iOS 11.3 Safari takes standalone from the manifest's
  // `display: "standalone"` instead. The legacy Apple meta is declared below as
  // a fallback for the one case that would otherwise be fatal: if the manifest
  // ever fails to load (e.g. gated by the auth proxy), the home-screen app still
  // launches chrome-less instead of degrading to a Safari tab.
  // statusBarStyle stays "default" (not black-translucent) because the layout
  // already pads for the safe area instead of drawing under the status bar.
  appleWebApp: { capable: true, title: "So-study", statusBarStyle: "default" },
  other: { "apple-mobile-web-app-capable": "yes" },
};

export const viewport: Viewport = {
  // Kept identical to `theme_color` in app/manifest.ts: iOS colours the
  // standalone status bar from this meta tag, so a drift between the two shows
  // up as a colour change the moment the app is installed.
  themeColor: "#4f46e5",
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="id"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ServiceWorkerRegister />
        {children}
      </body>
    </html>
  );
}
